USE [master]
GO

/****** Object:  Database [RazorBase]    Script Date: 25.08.2020 22:31:56 ******/
CREATE DATABASE [RazorBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RazorBase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RazorBase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RazorBase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RazorBase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RazorBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RazorBase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RazorBase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RazorBase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RazorBase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RazorBase] SET ARITHABORT OFF 
GO

ALTER DATABASE [RazorBase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RazorBase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RazorBase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RazorBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RazorBase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RazorBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RazorBase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RazorBase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RazorBase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RazorBase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RazorBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RazorBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RazorBase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RazorBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RazorBase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RazorBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RazorBase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RazorBase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RazorBase] SET  MULTI_USER 
GO

ALTER DATABASE [RazorBase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RazorBase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RazorBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RazorBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RazorBase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RazorBase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RazorBase] SET  READ_WRITE 
GO

